config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1) do
      resources :kittens
    end

    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: true) do
      resources :kittens
    end
  end

  resources :kittens
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
# == Schema Information
#
# Table name: kittens
#
#  id         :integer          not null, primary key
#  age        :integer
#  cuteness   :integer
#  name       :string
#  softness   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Kitten < ApplicationRecord
  validates :age, presence: true
  validates :cuteness, presence: true, numericality: { in: 0..5 }
  validates :name, presence: true
  validates :softness, presence: true, numericality: { in: 0..5 }
end

app/controllers/api/v1/kittens_controller.rb
module Api
  module V1
    class KittensController < ApplicationController
      class Kitten < ::Kitten
        def as_json(options = {})
          super(options.merge(except: [:created_at, :updated_at]))
        end
      end

      def index
        @kittens = Kitten.all
        respond_to do |format|
          format.json { render json: @kittens }
        end
      end

      def show
        @kitten = Kitten.find(params[:id])

        respond_to do |format|
          format.json { render json: @kitten }
        end
      end
    end
  end
end

app/controllers/api/v2/kittens_controller.rb
module Api
  module V2
    class KittensController < ApplicationController
      class Kitten < ::Kitten
        def as_json(options = {})
          super(options.merge(methods: [:random]))
        end

        def random
          rand(0..100)
        end
      end

      def index
        @kittens = Kitten.all
        respond_to do |format|
          format.json { render json: @kittens }
        end
      end

      def show
        @kitten = Kitten.find(params[:id])

        respond_to do |format|
          format.json { render json: @kitten }
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
  end

  def show
    @kitten = Kitten.find(params[:id])
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to kittens_path, notice: "Kitten created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: "Kitten updated"
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])

    @kitten.destroy

    redirect_to kittens_path, notice: "Kitten correctly destroyed"
  end

  private

  def kitten_params
    params.require(:kitten).permit(:age, :name, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<% unless @kitten.errors.empty? %>
  <div class="errors">
    <ul>
      <% @kitten.errors.full_messages.each do |error| %>
        <li>
          <%= error %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @kitten do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :cuteness %>
    <%= f.number_field :cuteness, min: 0, max: 5 %>
  </div>
  <div class="field">
    <%= f.label :softness %>
    <%= f.number_field :softness, min: 0, max: 5 %>
  </div>

  <%= f.submit %>  
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten %>
    </li>
  <% end %>
</ul>

<div class="actions">
  <%= link_to 'Create kitten', new_kitten_path %>
</div>

app/views/kittens/new.html.erb
<h1>New kitten</h1>

<%= render 'form' %>

app/views/kittens/show.html.erb
<h1>Show kitten</h1>

<h2>Name: <%= @kitten.name %></h2>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Solftness: <%= @kitten.softness %></p>

<div class="actions">
  <%= link_to 'Edit', edit_kitten_path %>
  <%= link_to 'Destroy', @kitten, data: {
    turbo_method: "delete",
    turbo_confirm: "Are you sure?"
  } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to 'Home', root_path %>
    <% unless flash.empty? %>
      <% flash.each do |type, msg| %>
        <div>
          <%= msg %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>